version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly
      time: a

  - package-ecosystem: docker
    directories:
    - /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /
      - /packages/**/*
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /terraform/**/*
    schedule:
      interval: weekly


groups:
  node-aws:
    patterns:
      - @aws-sdk/*
      - @effect-aws/*
      - @types/aws-lambda
  node-hapi:
    patterns:
      - hapi
      - @hapi/*
      - joi
  node-effect:
    patterns:
      - effect
      - @effect/*
  node-discord:
    patterns:
      - discord.js
      - @discordjs/*
      - discord-interactions
      - discord-api-types
  node-lint:
    patterns:
      - @commitlint/*
      - husky
      - typescript-eslint
      - eslint
      - @eslint/*
      - @stylistic/*
      - @types/eslint__js
